name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master    # 僅在 master 分支有推送時觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist   # Vite 構建輸出的資料夾
          branch: gh-pages   # 要部署到的分支
          clean: true    # 部署前清空分支

      # 成功通知
      - name: Send success message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Deploy success！
            專案: ${{ github.repository }}
            提交者: ${{ github.actor }}
            提交訊息: ${{ github.event.head_commit.message }}
            
      # 失敗通知
      - name: Send failure message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Deploy failure！
            專案: ${{ github.repository }}
            提交者: ${{ github.actor }}
            提交訊息: ${{ github.event.head_commit.message }}
            詳情請查看: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}